- seeding/refs-to-seed
This is the example filesystem used for my nsinit container demo
(ipfs/container-demos#22).  If/when that PR lands, merging this one
and running make will preserve the example filesystem even when my
IPFS daemon is not online.
> seeding/refs-to-seed: Add QmYRpzwXkSnCPPNL4b2gn5AFnyyMHFxhS9Nrbau5ycw92H

- solarnet/roles/common/tasks/main.yml
- solarnet/secrets.yml.example
Added gateway.ipfs.io keys to secrets.yml in https://github.com/protocol/infrastructure/commit/2e6555fbbcc844241a6da4b6bf13b6cde790aebb
> solarnet: set up authorized_keys

- solarnet/roles/ipfs_gateway/templates/nginx.conf.j2
- solarnet/roles/prometheus/files/Dockerfile
- solarnet/roles/prometheus/meta/main.yml
- solarnet/roles/prometheus/tasks/main.yml
- solarnet/roles/prometheus/templates/prometheus.yml.j2
- solarnet/roles/prometheus/vars/main.yml
- solarnet/solarnet.yml
Scrapes all gateway hosts' `/debug/metrics/prometheus` and provides a query API and UI.
See it in action: http://pluto.i.ipfs.io/prometheus/graph#[{%22range_input%22%3A%221h%22%2C%22end_input%22%3A%22%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22ipfs_p2p_peers_total%22%2C%22tab%22%3A0}]
Prometheus runs its default config, with only the scraping targets added. I left out authentication because I'm not sure it needs to be protected. @jbenet @whyrusleeping wdyt?
> solarnet: add prometheus on pluto

- solarnet/cleanup.sh
- solarnet/hosts
- solarnet/roles/ipfs/tasks/main.yml
- solarnet/roles/ipfs_gateway/templates/nginx.conf.j2
- solarnet/roles/prometheus/files/Dockerfile
- solarnet/roles/prometheus/tasks/main.yml
- solarnet/roles/prometheus/templates/prometheus.yml.j2
- solarnet/solarnet.yml
- gateway at http://[fc12::3456]:8080
- api at http://[fc12::3456]:5001
- prometheus at http://[fc12::3456]:80 / http://metrics.ipfs.io
All of them require authentication with a whitelisted
cjdns IPv6 address (see secrets.yml).
The other three commits are semi-random fixes.
> Make use of cjdns for Prometheus/API/Gateway authentication

- solarnet/roles/ipfs_gateway/templates/nginx.conf.j2
If coming in via the cjdns address, the metrics.ipfs.io host would incorrectly be used as the default host since it's more granular than [::].
> Fix nginx gateway vhost

- solarnet/roles/cjdns/tasks/main.yml
- solarnet/roles/common/tasks/main.yml
- solarnet/roles/docker/files/get-docker.sh
- solarnet/roles/docker/tasks/main.yml
- solarnet/roles/ipfs/tasks/main.yml
- solarnet/roles/ipfs_gateway/tasks/main.yml
- solarnet/roles/metrics/tasks/main.yml
- solarnet/roles/node_exporter/tasks/main.yml
These are fixes which were neccessary for rebuilding Pluto (others will follow). Most notably:
- install docker using vendored get.docker.ui script
- run the `nginx` image instead of the dead `dockerfile/nginx` image.
- set hostname from inventory file
> Fix bootstrapping of fresh hosts

- solarnet/roles/ipfs/tasks/main.yml
- solarnet/roles/ipfs/templates/config.j2
- solarnet/secrets.yml.example
No more lost private keys! Safely rebuild hosts! This is pretty much a standard config, but with MDNS disabled, and SupernodeRouting removed. The bootstrap nodes can be removed too, once we can discover peers from cjdns.
License: MIT
> ipfs: manage repo config with ansible

- solarnet/roles/common/tasks/main.yml
- solarnet/roles/docker/tasks/main.yml
- solarnet/roles/ipfs/tasks/main.yml
commit 35abbee97fa9a17b83126c3a6d901b449f2df397
Date:   Thu Jul 30 00:28:32 2015 +0200
ipfs: run ipfs init using one-shot container
Previously, when ipfs init hadn't been run yet, the
container would go into a restart loop, and thus
`docker exec` in that looping container would fail
to execute `ipfs init`.
License: MIT
commit 7842b7ce1e0def7b50ba17803231742d3cf6eba2
Date:   Thu Jul 30 00:27:22 2015 +0200
docker: pin to known-working docker-py 0.5.3
The latest is failing to recognize locally-built images
and always tries to pull them from the registry.
No idea why pip picked an old (but working) version
during the previous rebuild of pluto. Anyhow, I'm not
going …
> Bootstrap fixes

- solarnet/hosts
- solarnet/roles/ipfs/tasks/main.yml
- solarnet/roles/ipfs/templates/nginx_ipfs.conf.j2
- solarnet/roles/ipfs_gateway/tasks/main.yml
- solarnet/roles/ipfs_gateway/templates/nginx_ipfs_gateway.conf.j2
- solarnet/roles/ipfs_gateway/vars/main.yml
- solarnet/roles/metrics/tasks/main.yml
- solarnet/roles/metrics/templates/prometheus.yml.j2
- solarnet/roles/nginx/handlers/main.yml
- solarnet/roles/nginx/tasks/main.yml
- solarnet/roles/nginx/templates/nginx.conf.j2
- solarnet/roles/nginx/vars/main.yml
- solarnet/roles/node_exporter/tasks/main.yml
- solarnet/solarnet.yml
Since I added the first non-gateway host (scruffy), I needed to have nginx decoupled from IPFS.
Every host runs cjdns, nginx, and prometheus' node_exporter. The gateway hosts simply add vhosts to the nginx config.
> Decouple nginx from ipfs_gateway, move pinbot and metrics to scruffy

- solarnet/hosts
- solarnet/solarnet.yml
So that pinbot builds don't run out of memory, which is eaten up by Prometheus, see #56 
License: MIT
> solarnet: move pinbot to new host called willie

- .gitignore
- solarnet/.gitignore
- solarnet/README.md
- solarnet/secrets.sh
- solarnet/solarnet.yml
From the updated readme:
IPFS and cjdns private keys, SSL certificates, and cjdns peering credentials,
are tracked by Git in a secret repository, in encrypted form.
We need to decrypt them for usage, and encrypt them for committing changes.
```sh
$ git clone https://example.net/secrets.git secrets/
$ echo "the-key" > ../solarnet.key
$ ./secrets.sh -d
$ vim secrets_plaintext/secrets.yml
$ ./secrets.sh -e
$ cd secrets/
$ git add secrets.yml
$ git commit -m 'Add some password or so'
```
You can also pipe the key instead of writing it to a file:
```sh
$ echo "the-key" | ./secrets.sh -d
```
> secrets: rework how we store secrets

- solarnet/hosts
- solarnet/solarnet.yml
I take name suggestions, right now it's storage1.i.ipfs.io
> solarnet: add storage hosts sirius and pollux

- seeding/seed.sh
This makes seed.sh a bit nicer on memory usage (until go-ipfs#1222 gets fixed)
> Start a new process for each ref

- solarnet/roles/ipfs/templates/config.j2
Fixes ipfs/go-ipfs#1586
License: MIT
> ipfs: enable CORS for API

- solarnet/roles/ipfs_gateway/tasks/main.yml
- solarnet/roles/ipfs_gateway/templates/nginx_ipfs_gateway.conf.j2
It's already running on the gateways, and graded A by SSL Labs: https://www.ssllabs.com/ssltest/analyze.html?d=gateway.ipfs.io&latest
Closes #6 
- enable OCSP stapling
- bring in the StartSSL cert
- reload nginx for cert/key/dhparam changes
License: MIT
> gateway: get SSL cert signed by StartSSL

- solarnet/roles/ipfs_gateway/templates/nginx_ipfs_gateway.conf.j2
- solarnet/roles/nginx/handlers/main.yml
If the host is ipfs.io, and the request is for /ipfs or /ipns,
we don't pass the Host header on to the gateway,
so that IPNSHostnameOption doesn't trigger,
and the /ipfs and /ipns request can succeed.
For all other requests with a Host header and TXT record,
/ipfs and /ipns are not present.
> Make /ipfs and /ipns work with self-hosted ipfs.io

- solarnet/secrets.yml.example
- solarnet/users.yml
@rht @davidar @mikolalysenko you should all have access to pollux.i.ipfs.io and sirius.i.ipfs.io, using your github handle as the username.
If you want to run an IPFS node, please do so, but make sure to disable dialing local addresses, as describe here: https://github.com/ipfs/go-ipfs/issues/1226#issuecomment-120494604
Otherwise we get alerts from the hoster, and the host gets shut down if we don't react quickly enough.
There is one IPFS node running in a docker container which uses ports 4001, 5001, and 8080. You should be able to use that with the regular IPFS CLI, but in any case you can run your own node.
Any questions? We can amend that setup to whatever seems more appropriate.
> solarnet: add users playbook

- solarnet/metrics.yml
- solarnet/roles/docker/tasks/main.yml
- solarnet/roles/metrics/files/Dockerfile
- solarnet/roles/metrics/templates/prometheus.yml.j2
- solarnet/roles/node_exporter/templates/upstart_node_exporter.conf.j2
commit 91754c7dd3ead43f8fe3802b66a6fd7e49efdc7e
Date:   Mon Sep 21 19:42:31 2015 +0200
```
docker: make sure docker is enabled and started
License: MIT
```
commit bf89890010d2e71efca1db6d2a705f2bd931e2d2
Date:   Mon Sep 21 19:42:12 2015 +0200
```
docker: fix --log-driver migration
License: MIT
```
commit fc872adf1bca9824de58ea8b6709d110c64a14c6
Date:   Mon Sep 21 19:41:18 2015 +0200
```
prometheus: performance tuning
- scrape less often
- removed unused monitor label
- use less RAM, we were running out of it constantly
License: MIT
Signed-off-by: Lars Gierth …
```
> Monitoring fixes

- solarnet/cjdns.yml
- solarnet/common.yml
- solarnet/peering.sh
- solarnet/roles/cjdns/templates/cjdroute.conf.j2
- solarnet/roles/cjdns/vars/main.yml
- solarnet/secrets.yml.example
commit 2e31e24392e70b0c15217b2ea79582bc623c2698
Date:   Mon Sep 28 04:05:24 2015 +0200
```
cjdns: make peering.sh aware of different passwords
```
commit 65a0308c63dfc9c33278324aabe05bd380eaa5c3
Date:   Mon Sep 28 03:12:52 2015 +0200
```
cjdns: update to latest hyperboria:master
```
commit 47724d636c932422a806f7438a63857ee9265e09
Date:   Mon Sep 28 03:11:42 2015 +0200
```
cjdns: give peering.sh a host pattern argument
We might want to get peering details
for only a handful of hosts.
```
commit f016f61784cc054bc4fa51903946ffc5ff0f963d
Date:   Mon Sep 28 03:09:50 2015 +0200
```
cjdns: make use of peerName
Makes for more …
```
> Alexandria peering

- solarnet/roles/ipfs/files/Dockerfile
- solarnet/roles/ipfs/tasks/main.yml
- solarnet/roles/pinbot/files/Dockerfile
commit 253d9a4781904c6ed4afd9e4cece1b40ed278a8d
Date:   Fri Oct 23 03:17:04 2015 +0200
pinbot: base on golang:1.5.1 image
Alpine has go1.5 in their community repos,
but I have no idea how to make use of it.
We were using Alpine here to keep the image size down,
but these images never hit the wire anyhow.
License: MIT
commit 8e87963f504c655d529cbf7367d0922df7be0627
Date:   Fri Oct 23 03:48:52 2015 +0200
ipfs: base on golang:1.5.1 image
License: MIT
commit 1e75827d0f185f0b1359381389cbdf1dadc01d24
Date:   Fri Oct 23 03:49:44 2015 +0200
ipfs: use ipfs.ref file to trigger …
> golang1.5 for IPFS and Pinbot

- solarnet/roles/ipfs/templates/nginx_ipfs.conf.j2
- solarnet/roles/ipfs_gateway/templates/nginx_ipfs_gateway.conf.j2
commit 3dbe4deeb4197b495a5c0435077c498d76ec79cc
Date:   Fri Oct 23 04:56:54 2015 +0200
ipfs: make timeouts less likely
License: MIT
commit 4b9dea8f36f4eba7d7dbbcabf40393e2a23b3f64
Date:   Fri Oct 23 05:00:17 2015 +0200
gateway: don't fall back to other gateways for too long
License: MIT
> Nginx timeouts

- solarnet/roles/ipfs_gateway/templates/nginx_ipfs_gateway.conf.j2
Rewrites requests for `/refs/a/b/c` to `c.b.a.refs.ipfs.io`.
Also replaces conditionals with location directives,
which are evaluated more efficiently.
Part of the gateway-dmca-denylist thing: https://github.com/ipfs/go-ipfs/pull/1551 https://github.com/ipfs/gateway-dmca-denylist
> gateway: add /refs/*

- solarnet/README.md
- solarnet/secrets.sh
It should now be put into `$HOME/.protocol/solarnet.key` @whyrusleeping @jbenet 
I wanna do it similarly with dnslink-deploy and the Digitalocean key @RichardLitt
> secrets: move encryption key to a safer location

- solarnet/roles/ipfs_gateway/templates/nginx_ipfs_gateway.conf.j2
> gateway: set X-Ipfs-Gateway-Prefix header

- solarnet/roles/ipfs/templates/config.j2
> gateway: open up CORS to everything (allow-origin *)

- solarnet/roles/docker/tasks/main.yml
Docker can now rotate these container logs, which have been filling our disks in the past!
> docker: reactivate container logs

- solarnet/hosts
- solarnet/roles/ipfs/tasks/main.yml
- solarnet/roles/ipfs/templates/config.j2
Each host gets a couple GB headroom for docker containers/images, logs, and all the usual system stuff.
Doesn't quite seem to work yet: https://github.com/ipfs/go-ipfs/pull/1495#issuecomment-159801962
> ipfs: automatic GC

- solarnet/hosts
- solarnet/ipfs.yml
- solarnet/metrics.yml
- solarnet/roles/cjdns/templates/cjdroute.conf.j2
- solarnet/roles/metrics/templates/prometheus.yml.j2
cc @whyrusleeping @diasdavid @dignifiedquire
These two are the NUCs which we had at camp -- I'll bring them to congress too, so they'll finally get some combat experience :)
namaka runs dev040 and is already bootstrapped, while hiiaka will run master. I'm referencing them by their cjdns IP because they don't have a fixed IP address on their own. If we lose connectivity, we'll have to hook up a cable and do link-local SSH.
> solarnet: add edge hosts namaka and hiiaka

- oldnet/roles/common/tasks/main.yml
- oldnet/roles/ipfs/templates/nginx_ipfs.conf.j2
- oldnet/roles/ipfs_gateway/templates/nginx_ipfs_gateway.conf.j2
- oldnet/roles/metrics/templates/prometheus.yml.j2
- oldnet/roles/nginx/templates/nginx.conf.j2
- oldnet/roles/node_exporter/templates/nginx_node_exporter.conf.j2
- solarnet/env.sh
- solarnet/mtail/Dockerfile
- solarnet/mtail/build.sh
- solarnet/mtail/env.sh
- solarnet/mtail/install.sh
- solarnet/mtail/progs/nginx.mtail
We introduce github.com/google/mtail for parsing nginx logs, and exposing request and response metrics to Prometheus.
- The build and install scripts are more verbose than they'll eventually have to be. The whole container build, start, restart thing hasn't been generalized yet.
- Oldnet is being touched for exposing mtail's HTTP interface, and wiring it with Prometheus. These two aspects haven't been migrated to Provsn yet.
TODO: have the gateway dashboard use the metrics scraped from mtail (`s/handler="gateway"/job="mtail"`)
> Prometheus metrics from nginx logs

- ipfs/env.sh
Note: already have this running on nihal.
Putting the cowboy hat on, since the canaries lack 38 commits from master:
https://github.com/ipfs/go-ipfs/compare/9eba0e4ffbbf5230a54788e546ea822b357eea6f...8d6ac7a83f91089d536790f3db07ed653a8a1c04
The storage hosts have been on 0.4.3-rc3 and 0.4.4 respectively.
They haven't been updated as often because it sometimes requires
coordination with community members who use them for archives work.
Adding the CCC archive to nihal showed a few interesting things which
probably have been fixed on master -- such as the amount of effort
put into synchronizing provider records.
License: MIT
> ipfs: update everything to latest master

- ipfs/env.sh
It's already on. Note that apart from test-driving sharding (ipfs/go-ipfs#3042), this is a downgrade.
> ipfs: run sharding code on nihal, and update secrets

- env.sh
License: MIT
Closes ipfs/ops-requests#29
> vpn: add teamcity node

- ipfs/env.sh
This should be sufficient size for quite some time.
If we reach sizes of abotu GiB I will investigate file backed solution.
> Increase bloom filter size on storage hosts

- env.sh
- ipfs/env.sh
- ipfs/gateway/nginx.conf
This proxies the upgraded connection to :8081, where the /ws listener listens. Runs ipfs/go-ipfs@8291bd6ec6b9881a12ad6a137e78f5c3351b63cf.
The nicer solution is mounting the WebsocketTransport on the gateway within go-ipfs.
> ipfs: run gateway and /ws bootstrapper

- scripts/ipfs-debug.sh
This is installed on all hosts now and can be invoked like this:
```sh
> scp scripts/ipfs-debug.sh root@spacerock.i.ipfs.io:/root/
> ssh root@spacerock.i.ipfs.io /root/ipfs-debug.sh
...
https://ipfs.io/ipfs/QmTzqwxh2kjSQznZh8iYZzeXtQuHZ9pDkocxu184mKJqxd
```
> scripts: add ipfs-debug.sh script

- ipfs/env.sh
So I can try the ccc archive transfer with `ipfs pin add`, some improvements there.
License: MIT
> ipfs: update auva to master

- ipfs/gateway/denylist.conf
- ipfs/gateway/install.sh
- ipfs/gateway/nginx.conf
The /blog and /refs rewrites were applying to all IPNS websites too.
@daviddias pinged me about daviddias.me/blog returning ipfs.io/blog -- ooops!
This commit breaks up the gateway vhost into gateway and website.
Had it deployed for a week or so already, sorry about that :S
It also moves the denylist rules into their own file.
Closes #224
> gateway: separate ipfs.io website from ipfs.io gateway

- ipfs/env.sh
So that js-ipfs can use the same bootstrappers as go-ipfs, just over /tcp/ws instead of /tcp.
Temporarily until the /ws listener is properly muxed into the go-ipfs gateway.
> ipfs: update to v0.4.7 with /ws port exposed

- ipfs/config.tpl
This makes node startup faster, which benefits the availability of the gateway. Closes #269.
> ipfs: enable DisableNatPortMap

- scripts/dnslink.sh
I had to tweak `dnslink.sh` when testing it out on a new domain to use the property name `record_type` instead of `type` to get it to create a new TXT record where none previously exists. See https://developer.dnsimple.com/v1/domains/records/#create
> Fix dnslink.sh issue when creating new TXT record

- env.sh
- ipfs-cluster/README.md
- ipfs-cluster/build.sh
- ipfs-cluster/env.sh
- ipfs-cluster/install.sh
- ipfs-cluster/service.json.tpl
- ipfs/env.sh
The changes in this commit allow provsn to deploy an ipfs-cluster
container along with the ipfs-one in the 10 nodes that ipfs-bot uses.
> Add ipfs-cluster unit

- ipfs-cluster/service.json.tpl
This will make cluster call repo/stat 10x times less. It's deployed already.
> cluster: Increase disk informer interval

- metrics/prometheus/prometheus.yml.tpl
Currently unprotected /prometheus endpoint on jenkins, but AFAIK, there is no secret values there or any actions that could be performed via the endpoint.
> Add jenkins scraping to prometheus

- metrics/prometheus/prometheus.yml.tpl
Already been deployed, but this commit makes it permanent!
> Add targets for docker + cadvisor on cloud.ipfs.team

- ipfs/env.sh
Exposes API methods for delegated routing on the gateway.
License: MIT
> ipfs: update to ipfs/go-ipfs#4595

- env.sh
- ipfs/build.sh
- ipfs/env.sh
Nodes were at 0.4.17 and 0.4.16-rc2, respectively. Yikes.
> upgrade IPFS to v0.4.21
