ipfs/infra

- seeding/refs-to-seed
License: MIT
Signed-off-by: Henry <cryptix@riseup.net>
> seed nicer go-ipfs index page assets

- solarnet/roles/cjdns/tasks/main.yml
- solarnet/roles/common/tasks/main.yml
- solarnet/solarnet.yml
A few things that I somehow missed during my pluto-driven development.
> Monitoring fixups

- README.md
- solarnet/Makefile
- solarnet/roles/pinbot/files/Dockerfile
- solarnet/roles/pinbot/tasks/main.yml
- solarnet/roles/pinbot/templates/hosts.j2
- solarnet/roles/pinbot/vars/main.yml
- solarnet/solarnet.yml
> pinbot: run pinbot on pluto and neptune

- solarnet/roles/ipfs_gateway/tasks/main.yml
- solarnet/roles/ipfs_gateway/templates/nginx_ipfs_gateway.conf.j2
- solarnet/roles/nginx/tasks/main.yml
> gateway: offer https with self-signed cert

- solarnet/roles/ipfs/templates/config.j2
See: https://github.com/ipfs/go-ipfs/issues/1226
License: MIT
> ipfs: don't randomly dial local networks

- solarnet/hosts
> solarnet: stick with spacerocks naming

- solarnet/roles/common/tasks/main.yml
> Install tmux

- solarnet/roles/ipfs/templates/config.j2
> gateway: set CORS headers for https:// too

- solarnet/common.yml
- solarnet/roles/docker/handlers/main.yml
- solarnet/roles/docker/tasks/main.yml
Had this sitting around in a git-stash since last week...
> docker: disable container logs, closes #29

- solarnet/metrics.yml
- solarnet/roles/metrics/templates/prometheus.yml.j2
> metrics: include hostname in metrics labels

- solarnet/Makefile
- solarnet/requirements.txt
- solarnet/roles/docker/tasks/main.yml
- solarnet/roles/ipfs/tasks/main.yml
Ansible needs docker-py 1.5, which needs a Docker update.
License: MIT
> solarnet: update ansible

- solarnet/hosts
- solarnet/pinbot.yml
- solarnet/roles/pinbot/templates/hosts.j2
> pinbot: exclude dev0.4.0 hosts, they can't reach the stuff

- README.md
- astralboot/README.md
Base folders and README skeleton for astralboot.
> Adding astralboot initial

- solarnet/full.sh
- solarnet/hosts
- solarnet/roles/ipfs/templates/config.j2
- solarnet/roles/node_exporter/defaults/main.yml
- solarnet/users.yml
- S'ad al-Biham -- Lucky Star of the Young Beasts (https://en.wikipedia.org/wiki/Theta_Pegasi)
- An-Nihal -- The camels quenching their thirst (https://en.wikipedia.org/wiki/Beta_Leporis)
nihal will be used for cube, biham will be mainly archives and npm.
castor and sirius are now deprecated, their homes and repos will be moved to biham.
> Add storage hosts biham and nihal

- solarnet/roles/ipfs/files/Dockerfile
- solarnet/roles/ipfs/tasks/main.yml
> ipfs: build with makefile, enables commit in :8080/version

- solarnet/hosts
OVH shut it off today as I didn't extend payment
> solarnet: decomission castor

- seeding/refs-to-seed
Ref https://github.com/ipfs/go-ipfs/pull/2188
> Add new webui

- ipfs/env.sh
Should somewhat fix accumulation of goroutines, and improve GC perf.
Already running on neptune and mercury.
> ipfs: update to latest master

- env.sh
@benhylau is one of the fc00 and Toronto Meshnet folks. They're starting to build their meshnet in Toronto and are thinking about how to monitor it, and he wants to see our grafana+prometheus+cjdns setup.
> vpn: allow benhylau

- README.md
- ansible/README.md
- base/README.md
- docker/README.md
- ipfs/README.md
- provsn.md
Initial version of some documentation. First pass.
Part of https://github.com/ipfs/infrastructure/issues/185 and making the documentation better.
Missing things, maybe this is something we can work together on. @lgierth please add/change anything you seem fit.
@hsanjuan @Kubuxu please mention things you think is missing from our documentation so we can add it.
> More documentation

- README.md
Added a quick explanation on how to add your ssh key.
> Add ssh access instructions

- ipfs/env.sh
> ipfs: update some to master, enable mplex experiment

- ipfs/env.sh
They have a pinning bugfix which apparantly was responsible for pinbot acting up..
> ipfs: update non-mplex gateways

- ansible/roles/pinbot/defaults/main.yml
- ansible/roles/pinbot/files/Dockerfile
- ansible/roles/pinbot/templates/hosts.j2
The improved output has helped in debugging the pinbot issues.
> pinbot: update for better output, and *.v.ipfs.team domains

- base/env.sh
- env.sh
- metrics/prometheus/env.sh
- metrics/prometheus/prometheus.yml.tpl
> metrics: scrape jenkins

- ci/jenkins/build.sh
- ci/jenkins/install.sh
- ci/jenkins/nginx.conf.tpl
- env.sh
- metrics/prometheus/prometheus.yml.tpl
This doesn't include port 443 and the SSL cert yet.
> jenkins: add nginx config for web and metrics

- sprintbot/README.md
This should help when things happen like they did today. cc @victorbjelkholm @lgierth
> Add a sprintbot folder and README

- ci/jenkins/build.sh
- ci/jenkins/install.sh
- ci/jenkins/nginx.conf.tpl
- env.sh
- ipfs/gateway/build.sh
- ipfs/gateway/install.sh
- ipfs/gateway/nginx.conf
- ssl/build.sh
- ssl/install.sh
- ssl/nginx.conf
> SSL for ci.ipfs.team

- env.sh
- ipfs/pages/build.sh
- ipfs/pages/install.sh
- ipfs/pages/nginx.conf.tpl
Forgot opening this one... it's already on: https://orbit.chat
> pages: add orbit.chat

- ipfs/env.sh
> ipfs: test fs-repo-migration 4-to-5

- ipfs/env.sh
- ipfs/install.sh
Not updating all the nodes yet, I'm too lazy to do the DNS dance by hand. Will instate a proper DNS service first, so this gets a bit easier.
> Update a few nodes to fs-repo@5

- sprintbot/README.md
@lgierth can you give it access to protocol/pm?
> Add @ipfs-helper note

- ipfs/env.sh
> ipfs: disable routing on auva, for better performance

- ipfs/env.sh
> ipfs: update gateways to v0.4.7

- ipfs/gateway/nginx.conf
- ipfs/install.sh
Will write postmortem tomorrow.
Also includes a tiny change in preparation for ipfs/go-ipfs#3744
> gateway: fix /ipfs on ipfs.io (oops)

- nginx/nginx.conf
> nginx: enable gzip compression

- ipfs/env.sh
> ipfs: enable pubsub on all nodes

- ipfs/pages/nginx.conf.tpl
> pages: redirect ipn.io to protocol.ai

- ipfs/pages/nginx.conf.tpl
> pages: redirect wikipedia-on-ipfs.org to blog post

- ipfs/env.sh
Contains a few nice performance fixes
> ipfs: test-drive latest master

- ansible/roles/pinbot/defaults/main.yml
- ansible/roles/pinbot/files/Dockerfile
- ansible/roles/pinbot/tasks/main.yml
- ansible/roles/pinbot/templates/clusterpeers.j2
- ipfs-cluster/build.sh
- ipfs-cluster/env.sh
- ipfs-cluster/install.sh
- ipfs-cluster/nginx.conf
This uses the latest pinbot and provides connectivity to the cluster API.
> Update pinbot with new ipfs/ location and cluster capabilities

- ipfs/gateway/denylist.conf
@VictorBjelkholm how does this look? I went over the old stuff and gave everything a 410 status code that wasn't a legally binding takedown.
> gateway: be more differentiated about blocklist status codes

- ipfs/env.sh
- ipfs/gateway/nginx.conf
- ipfs/install.sh
Live on scrappy and chappy so @dignifiedquire can test it with js-libp2p-delegated-routing
> gateway: delegated routing

- ipfs/install.sh
> ipfs: fix init check wrt badgerds

- .github/ISSUE_TEMPLATE.md
Add a simple template for when users create new Issues.
> Add Issue template

- env.sh
> Fix metrics collector
